services:
  - type: web
    name: mon-app-rails-sans-db
    env: ruby
    plan: free
    region: frankfurt
    branch: main

    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        value: <votre_secret_key_base>

    buildCommand: |
      bundle install --jobs 4 --retry 3
      bundle exec rake assets:precompile

    startCommand: bundle exec puma -C config/puma.rb
    healthCheckPath: /
